# Generated by Django 5.0.3 on 2024-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_post_video_remove_post_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
