# Generated by Django 5.0.3 on 2024-08-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_show_on_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='show_on_homepage',
        ),
    ]
