# Generated by Django 5.0.3 on 2024-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_post_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('catering', 'Catering'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('cleaning', 'Cleaning'), ('marketing', 'Marketing'), ('hand man', 'hand man'), ('photographer', 'Photographer'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
