# Generated by Django 5.0.3 on 2024-08-27 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/undraw_Blogging_re_kl0d-removebg-preview.png', upload_to='category_images/'),
        ),
    ]
