# Generated by Django 5.0.3 on 2024-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_servicepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepicture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepicture',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_pics'),
        ),
        migrations.AddField(
            model_name='servicepicture',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
