# Generated by Django 5.0.3 on 2024-08-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_servicepicture_description_servicepicture_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepicture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='price',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='services_offered',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='submit.profile')),
            ],
        ),
    ]
