# Generated by Django 5.0.3 on 2024-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_remove_servicepicture_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('catering', 'Catering'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('cleaning', 'Cleaning'), ('marketing', 'Marketing'), ('hand man', 'hand man'), ('photographer', 'Photographer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
