# Generated by Django 5.0.3 on 2024-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_alter_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, choices=[('catering', 'Catering'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('cleaning', 'Cleaning'), ('marketing', 'Marketing'), ('hand man', 'hand man'), ('photographer', 'Photographer'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
