# Generated by Django 4.2.11 on 2024-09-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0013_remove_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServicePicture',
        ),
    ]
